# .github/workflows/ansible-lint.yml

name: Ansible Lint

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    name: Ansible Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and ansible-lint
        run: |
          pip install "ansible-core==2.16.11" "ansible-lint==25.5.0"

      - name: Get modified files (YAML Only)
        id: detect_changes
        run: |
          EXCLUDE_DIRS="templates/|library/|files/"
          EXCLUDE_FILES="\\.git.*|\\.ansible.*\\..*lint.*"

          MODFILE_LIST=$(git diff --name-only --diff-filter=AM origin/${{ github.base_ref }} | grep -E '\.ya?ml$' | grep -vE "$EXCLUDE_DIRS|$EXCLUDE_FILES" || true)

          if [ -z "$MODFILE_LIST" ]; then
            echo "No files to lint. Exiting."
            echo "HAS_FILES=false" >> $GITHUB_ENV
          else
            echo "Files to lint:"
            echo "$MODFILE_LIST"
            echo ""
            ansible-lint --offline --profile production --skip-list=var-naming ${MODFILE_LIST}
          fi
